---
title: セクション2のまとめ(L36)
page-layout: full
title-block-banner: true
comments: false
---

おめでとうございます!

まずは、R言語というとっつきづらいプログラミング言語を専門外である医療職のあなたがここまで 学習を進めたこと、ご自身でご自身を褒めてあげてください。

医療職でないというかたも、もちろん、自分を褒めることに躊躇せず、どんどん褒めてあげましょう。

さて、ここまであなたにご提示した情報としては、

-   R studio の基本的な使い方
-   プロジェクトの概念
-   コメント
-   数値型、文字型
-   変数
-   ベクトル
-   データフレーム
-   パッケージ
-   関数

について説明しました。

それぞれの部分で取り扱った関数は、

| Col1           | Col2               |
|----------------|--------------------|
| 型             | as.numeric()       |
|                | as.character()     |
| ベクトル       | c()                |
| データフレーム | data.frame()       |
|                | View()             |
| パッケージ     | install.packages() |
|                | library()          |
| 関数           | sum()              |
|                | summary()          |
|                | unique()           |
|                | sort()             |
　
11個の関数です。 それぞれの関数がどんな働きをするか、見てイメージがでてくる状態でしょうか？

プログラミング言語の学習について、 個人的な意見ですが、「外国語の習得」と近い要素があると思っています。

習熟していくなかで、関数単体を読んだときに、その関数の働きがぱっと頭の中でイメージ できるようになることが、上達の第1歩だと 考えております。

なので、もし、ここでお示しした関数のなかで動作のイメージが怪しいものがあれば、是非 該当する部分の動画を見返しておいてください。

ここまでの解説、プログラミング言語の基礎としては、抜けているところも多々あると思います。

ただ、意図的に基礎のセクションで紹介していません

本コースの目的は、あくまで医療職/非エンジニアが、Rでデータ分析を行うためのとっかかり として、基本的な部分の習得を目的としています。

このセクションでは、次のセクション以降、最低限知っておかないといけない知識だけを 盛り込みました。

今後も、必要に応じて基本的な部分の説明を行います「必要と思ったとき」に勉強するのが 一番学習効率がよいと考えるからです。

それでは、ご一緒に、楽しくて、奥深い、Rでのデータ分析の世界にさらに足を踏み入れましょう！！
